name: amedspor_app
description: Amedspor odaklı maç sonuçları, fikstür, kadro, istatistikler ve haberler uygulaması.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.3.6
  dio: ^5.4.0
  cached_network_image: ^3.3.1
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_functions: ^4.4.2
  firebase_database: ^10.4.7
  firebase_messaging: ^14.7.10
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_mobile_ads: ^3.0.0
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  fl_chart: ^0.66.2
  webview_flutter: ^4.4.4
  url_launcher: ^6.2.5
  connectivity_plus: ^5.0.2
  json_annotation: ^4.8.1
  supabase_flutter: ^2.3.4
  equatable: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
